## baseline physics model

In [1]:
import pandas as pd
df = pd.read_csv('final_data_physics_baseline/physics_basedate.csv')
df = df.set_index('date')
df.drop(columns= 'Unnamed: 0', inplace= True)
df.head()

,dewpoint,et_loss,ndvi,precipitation,radiation,sca,dd,temp,runoff
date,,,,,,,,,
2000-06-30,270.274111,0.035384,0.167895,1.081265,8552.215167,15695.091988,0.0,253.924696,1.009778
2000-07-31,275.634907,0.005471,0.214835,2.074423,8945.476526,6188.434963,0.0,251.865719,0.543038
2000-08-31,273.643363,0.016486,0.171795,1.208544,8787.250911,10114.130241,0.0,256.913569,0.373700
2000-09-30,266.780844,0.040531,0.148384,0.857759,7687.016192,12888.810599,0.0,263.094486,0.196165
2000-10-31,259.412862,0.029951,0.113129,0.231264,5685.865842,19583.623736,0.0,271.551964,0.145426

In [2]:
df1 = df.copy()

In [23]:
#for single column dataframes always use double brackets, single brackets will make it a series, or float type
# for adding two columns to a df either add them one by one or use two brackets

In [20]:
X = df1.drop(columns= 'runoff')
Y = df1[['runoff']]

In [25]:
x_train = X[:'2017-12-31']
x_val = X['2018-01-01':'2021-12-31']
x_test = X['2022-01-01':]

y_train = Y[:'2017-12-31']
y_val = Y['2018-01-01':'2021-12-31']
y_test = Y['2022-01-01':]

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(x_train)
# x_train = scaler.transform(x_train)
# x_val = scaler.transform(x_val)
# x_test = scaler.transform(x_test)

StandardScaler()

In [27]:
from sklearn.linear_model import LinearRegression
def create_lag(df, lag_months):
    df['sca_lagged'] = df['sca'].shift(lag_months)
    df['dd_lagged'] = df['dd'].shift(lag_months)

    df['melt_proxy'] = df['sca_lagged']*df['dd_lagged']
    df_clean = df.dropna()

    return df_clean

In [28]:
import numpy as np
def calculate_nse(observed, predicted):
    mean_obs = np.mean(observed)
    numerator = np.sum((observed - predicted) ** 2)
    denominator = np.sum((observed - mean_obs) ** 2)
    return 1 - (numerator / denominator)

In [29]:
y_train.head()

              runoff
date
2000-06-30  1.009778
2000-07-31  0.543038
2000-08-31  0.373700
2000-09-30  0.196165
2000-10-31  0.145426

In [35]:
x = create_lag(df1, lag_months=2)
x_validation = create_lag(df1, lag_months=2)
X_train = x[['precipitation','melt_proxy']]
Y_train = y_train['runoff']
X_train.head(10)

            precipitation     melt_proxy
date
2000-08-31       1.208544       0.000000
2000-09-30       0.857759       0.000000
2000-10-31       0.231264       0.000000
2000-11-30       0.161151       0.000000
2000-12-31       0.175427       0.000000
2001-01-31       0.063452   69294.561299
2001-02-28       0.122006  278068.876829
2001-03-31       0.349344  202742.877343
2001-04-30       0.510792   37688.636114
2001-05-31       0.413804       0.000000

In [ ]:
lag_scaler st
# Y_val = y_val['runoff']
# X_val = x[['precipitation','melt_proxy']]

# x_train = scaler.transform(X_train)
# x_val = scaler.transform(x_val)
# x_test = scaler.transform(x_test)

# model = LinearRegression()
# model.fit(x_train, Y_train)
# Y_val = y_val['runoff']
# X_val= x['precipitation','melt_proxy']

# y_val_pred = model.predict(Y_val)
# baseline_nse = calculate_nse(Y_val, y_val_pred)

              dewpoint   et_loss      ndvi  precipitation    radiation  \
date
2000-08-31  273.643363  0.016486  0.171795       1.208544  8787.250911
2000-09-30  266.780844  0.040531  0.148384       0.857759  7687.016192
2000-10-31  259.412862  0.029951  0.113129       0.231264  5685.865842
2000-11-30  253.090692  0.087681  0.332089       0.161151  3036.950592
2000-12-31  247.389789  0.026067  0.320347       0.175427  1635.306735

                     sca       dd        temp    runoff    sca_lagged  \
date
2000-08-31  10114.130241  0.00000  256.913569  0.373700  15695.091988
2000-09-30  12888.810599  0.00000  263.094486  0.196165   6188.434963
2000-10-31  19583.623736  0.00000  271.551964  0.145426  10114.130241
2000-11-30  21183.674218  3.27113  276.271130  0.086778  12888.810599
2000-12-31  36902.800385  7.53517  280.535170  0.057378  19583.623736

            dd_lagged  melt_proxy
date
2000-08-31        0.0         0.0
2000-09-30        0.0         0.0
2000-10-31        0.0         0.0
2000-11-30        0.0         0.0
2000-12-31        0.0         0.0

            precipitation  melt_proxy
date
2000-08-31       1.208544         0.0
2000-09-30       0.857759         0.0
2000-10-31       0.231264         0.0
2000-11-30       0.161151         0.0
2000-12-31       0.175427         0.0